### ISSUE TITLE
StringIndexOutOfBoundsException in Lexer.java: 569

### ISSUE THREAD

**Issue by gavares** [neuland/jade4j#55] opened 2013-09-20 17:19 UTC
Looking into this on my end, I'll try to get a little more info about what is causing this but looking at Lexer.java it seems that there is another exception that should be getting thrown with a more informative message.

StackTrace

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1911) ~[na:1.7.0_11]
        at de.neuland.jade4j.lexer.Lexer.attributes(Lexer.java:569) ~[jade4j-0.3.15.jar:na]
        at de.neuland.jade4j.lexer.Lexer.next(Lexer.java:148) ~[jade4j-0.3.15.jar:na]
        at de.neuland.jade4j.lexer.Lexer.lookahead(Lexer.java:191) ~[jade4j-0.3.15.jar:na]
        at de.neuland.jade4j.parser.Parser.lookahead(Parser.java:697) ~[jade4j-0.3.15.jar:na]
        at de.neuland.jade4j.parser.Parser.peek(Parser.java:701) ~[jade4j-0.3.15.jar:na]
```

**Comment by FinalGuy** [comment] 2015-10-06 09:08
No further response from reporter, so i guess the problem is fixed? Closing this issue.

**Closed by FinalGuy** 2015-10-06 09:08 UTC
