### ISSUE TITLE
Numeric entities in rendered template

### ISSUE THREAD

**Issue by ki77y** [neuland/jade4j#151] opened 2017-01-11 13:30 UTC
I'm using jade4j to render xml from jade templates. 
Is there option to encode special characters as numeric entities instead of named entites? 
for example 
& oacute ; ===> &# 243 ;

**Comment by naltatis** [comment] 2017-01-12 17:19
No, currently only html escaping is supported:
https://github.com/neuland/jade4j/blob/master/src/main/java/de/neuland/jade4j/compiler/Utils.java#L125
It would definitly make sense to use `escapeXml` instead of `unescapeHtml4` when jade is in xml mode.

**Comment by gijoerg** [comment] 2019-09-17 09:01
It is a duplicate of #65 -> wontfix -> Closed

**Closed by gijoerg** 2019-09-17 09:01 UTC
